# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'toDoApp_rails' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for toDoApp_rails

pod 'Alamofire', '~> 5.2'
pod'SwiftyJSON'

end
